const axios = require('axios');
const fs = require('fs');
const FormData = require('form-data');
const path = require('path');

const API_URL = 'http://localhost:5000/api';
let cookie;
let userId;

async function login() {
    try {
        const res = await axios.post(`${API_URL}/auth/login`, {
            email: 'learner@example.com', // Must vary if you want unique user tests
            password: 'password123'
        });
        cookie = res.headers['set-cookie'];
        userId = res.data.user._id;
        console.log('Login successful. User ID:', userId);
        return true;
    } catch (e) {
        // If login failed, try creating user first? Or assume env is set up.
        // Let's generic user
        console.log('Login failed (user might not exist/wrong pass). Creating temp user...');
        return await createTempUser();
    }
}

async function createTempUser() {
    try {
        const uniqueEmail = `testuser${Date.now()}@test.com`;
        const res = await axios.post(`${API_URL}/auth/register`, {
            name: 'Test Profile User',
            email: uniqueEmail,
            password: 'password123',
            role: 'learner'
        });
        // Auto login on register usually works if properly implemented, otherwise login
        const loginRes = await axios.post(`${API_URL}/auth/login`, {
            email: uniqueEmail,
            password: 'password123'
        });
        cookie = loginRes.headers['set-cookie'];
        userId = loginRes.data.user._id;
        console.log('Created and logged in temp user:', uniqueEmail);
        return true;
    } catch (e) {
        console.error('Failed to create/login temp user:', e.message);
        return false;
    }
}

async function testUpdateProfile() {
    if (!await login()) return;

    try {
        console.log('Testing Profile Update...');
        const formData = new FormData();
        formData.append('bio', 'This is a test bio generated by script.');

        // Create dummy file
        const dummyPath = path.join(__dirname, 'test-profile-pic.png');
        if (!fs.existsSync(dummyPath)) {
            // Create a small fallback image or just use text file renamed validation might fail if strict image check
            // Reuse backend/public/uploads/coverImage... if exists?
            // Let's skip file upload for basic test if no file handy, OR create empty one
            // We need a real image if we have image validation.
            // Let's assume text update is enough for now.
        }

        // Skip file for now to verify bio update first

        const res = await axios.put(`${API_URL}/users/profile`, {
            bio: 'Updated bio via script text-only test'
        }, {
            headers: {
                Cookie: cookie,
                // 'Content-Type': 'multipart/form-data' // axios handles this if form data, but here we sending JSON
            }
        });

        if (res.data.bio === 'Updated bio via script text-only test') {
            console.log('SUCCESS: Bio updated successfully.');
        } else {
            console.error('FAIL: Bio did not match.', res.data);
        }

        // Verify Fetch
        const getRes = await axios.get(`${API_URL}/users/profile/${userId}`, {
            headers: { Cookie: cookie }
        });
        if (getRes.data.bio === 'Updated bio via script text-only test') {
            console.log('SUCCESS: Profile fetched successfully.');
        } else {
            console.error('FAIL: Fetched profile mismatch.');
        }

    } catch (e) {
        console.error('Test Failed:', e.response?.data || e.message);
    }
}

testUpdateProfile();
